version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: car-marketplace
    hostname: web
    container_name: web
    ports:
      - "8000:8000"
    command: ["/bin/bash", "./bash/run_web.sh"]
    env_file:
      - envs/web.env
    volumes:
      - ./:/code
